import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Wifi, X } from "lucide-react";
import { cn } from "../lib/utils";
import SidebarItem from "./SidebarItem";
const Sidebar = ({ items, activeRoute, state, mobileOpen, onCloseMobile }) => {
    const collapsed = state === "collapsed" && !mobileOpen;
    return (_jsxs("aside", { className: cn("fixed inset-y-0 z-40 flex w-72 flex-col border-r border-border/60 bg-card/80 pb-6 pt-6 shadow-[var(--shadow-soft)] backdrop-blur-2xl transition-transform duration-300", collapsed ? "lg:w-24" : "lg:w-72", mobileOpen ? "translate-x-0" : "-translate-x-full", "lg:translate-x-0"), children: [_jsxs("div", { className: cn("flex items-center justify-between px-6", collapsed && "px-4 lg:justify-center"), children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "rounded-2xl border border-border/60 bg-background/60 p-2 text-primary shadow-soft", children: _jsx(Wifi, { className: "h-5 w-5" }) }), !collapsed && (_jsxs("div", { children: [_jsx("p", { className: "text-[0.6rem] uppercase tracking-[0.35em] text-muted-foreground", children: "IoT Portal" }), _jsx("p", { className: "text-lg font-semibold text-card-foreground", children: "Command" })] }))] }), _jsxs("button", { type: "button", className: "rounded-full border border-border/70 bg-background/80 p-2 text-muted-foreground transition hover:text-foreground lg:hidden", onClick: onCloseMobile, children: [_jsx(X, { className: "h-4 w-4" }), _jsx("span", { className: "sr-only", children: "Close navigation" })] })] }), _jsx("nav", { className: cn("mt-8 flex-1 space-y-2 px-4", collapsed && "px-2"), children: items.map((item) => (_jsx(SidebarItem, { icon: item.icon, href: item.href, label: item.label, badge: item.badge, active: activeRoute === item.id, showLabel: !collapsed }, item.id))) }), _jsx("div", { className: cn("mt-auto px-6", collapsed && "px-3"), children: collapsed ? (_jsxs("div", { className: "hidden lg:flex flex-col items-center gap-2 rounded-2xl border border-border/70 bg-background-muted/30 px-2 py-4 text-[0.65rem] uppercase tracking-[0.35em] text-success", children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-success" }), "Live"] })) : (_jsxs("div", { className: "rounded-2xl border border-border/70 bg-background-muted/40 p-4 text-xs text-muted-foreground", children: [_jsx("p", { className: "font-semibold text-card-foreground", children: "Edge mesh health" }), _jsx("p", { className: "mt-1 text-muted-foreground", children: "Synchronizing clusters\u2026" }), _jsxs("div", { className: "mt-3 flex items-center gap-2 text-[0.65rem] uppercase tracking-[0.3em] text-success", children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-success" }), "Live"] })] })) })] }));
};
export default Sidebar;
